name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
env:
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  win-build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: dotnet publish Yona.Desktop -c Release -o build

    - name: Zip Build
      run: Compress-Archive -Path build/* -DestinationPath yona-windows.zip

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: win-build
        path: yona-windows.zip
        retention-days: 0

  linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: dotnet publish Yona.Desktop -c Release -o build

    - name: Zip Build
      run: |
        cd build
        tar -czvf ../yona-linux.tar.gz .

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: yona-linux.tar.gz
        retention-days: 0
   
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ win-build, linux-build  ]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      
      - name: AutoChangelog
        run: npm install -g auto-changelog

      - name: Create Changelog
        run: auto-changelog --sort-commits date --hide-credit --template keepachangelog --commit-limit false --starting-version "$env:RELEASE_TAG"

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            artifacts/**
            CHANGELOG.md
          fail_on_unmatched_files: true
