name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: dotnet publish Yona.Desktop -c Release -o build
    
    - name: Zip Build
      run: |
        cd build
        zip -r ../Release.zip ./*

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: Release.zip
        retention-days: 0
           
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Release.zip
        fail_on_unmatched_files: true
