name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  win-build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: dotnet publish Yona.Desktop -c Release -o build

    - name: Zip Build
      run: Compress-Archive -Path build/* -DestinationPath yona-windows.zip

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: win-build
        path: yona-windows.zip
        retention-days: 0

  linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: dotnet publish Yona.Desktop -c Release -o build

    - name: Zip Build
      run: tar -czvf yona-linux.tar.gz /build/*

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: yona-linux.tar.gz
        retention-days: 0
   
  release:
    if: startsWith(github.ref, 'refs/tags/')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          fail_on_unmatched_files: true
