name: Testing

on:
  workflow_dispatch:

env:
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: |
        if [ $IS_RELEASE = 'true' ]; then
          dotnet publish Yona.Desktop -c Release -o build /p:Version=$RELEASE_TAG
        else
          dotnet publish Yona.Desktop -c Release -o build
        fi

    - name: Folders
      run: |
        find build -type f
        find Yona.Desktop -type f